apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pangea-operator
  labels:
    app.kubernetes.io/name: pangea
    app.kubernetes.io/component: operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pangea-operator
subjects:
  - kind: ServiceAccount
    name: pangea-operator
    namespace: pangea-system
