---
apiVersion: v1
kind: Service
metadata:
  name: pangea-operator
  labels:
    app.kubernetes.io/name: pangea
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: pangea
spec:
  type: ClusterIP
  ports:
    - name: health
      port: 8080
      targetPort: health
      protocol: TCP
    - name: graphql
      port: 8081
      targetPort: graphql
      protocol: TCP
  selector:
    app.kubernetes.io/name: pangea
    app.kubernetes.io/component: operator
